name: Release

on:
  push:
    tags:
      - 'v*' # e.g., v1.0.5

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      # Set build-time version from git tag (drives webpack %VERSION% substitution)
      - name: Set build version from Git tag
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Using tag version: $VERSION"
          npm version --no-git-tag-version "$VERSION"

      - name: Install frontend deps
        run: npm ci

      - name: Build frontend (creates dist/ and dist/plugin.json)
        run: npm run build

      - name: Build backend (Mage BuildAll without installing mage)
        run: go run github.com/magefile/mage -v BuildAll

      # Package & validate; expects dist/ to exist already
      - name: Package plugin
        uses: grafana/plugin-actions/package-plugin@main
        with:
          node-version: 22
          go-version: 1.21
          backend-target: buildAll
